spring.application.name=patient-service

## Enable the H2 web console
#spring.h2.console.enabled=true
#
## Set the path to access the console (default is /h2-console)
#
#spring.h2.console.path=/h2-console
#
## Database connection settings
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#
## Optional: Ensure Hibernate generates the schema automatically
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

server.port=4000

logging.level.root=INFO